clean:
  rm ./node_modules/**/*.md
  rm ./node_modules/**/*.html
  rm ./node_modules/**/.travis.yml
  rm ./node_modules/**/.npmignore
  rm ./node_modules/**/Gruntfile.js
  rm ./node_modules/**/.testem.json
  rm ./node_modules/**/.jshintrc
  rm ./node_modules/**/.gitattributes
  rm ./node_modules/**/component.json
  rm ./node_modules/**/.documentup.json
  rm -r ./node_modules/**/.bin
  rm -r ./node_modules/**/test
  rm -r ./node_modules/**/example
  rm -r ./node_modules/**/examples